apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: uwv-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: portal
  ports:
    # Externe poort 80 → oauth2-proxy:4180. nginx (8080) is intern.
    - name: http
      port: 80
      targetPort: 4180
