apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uwv-platform
resources:
  - trino-static-auth.yaml
  - trinocluster.yaml
  - ingress.yaml
  - catalogs/rendered  # gegenereerd door scripts/render-trino-catalogs.py
