apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../platform/18-om-access-bridge
patches:
  - target:
      kind: Ingress
      name: om-access-bridge
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: platform.eu-sovereigndataplatform.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: platform.eu-sovereigndataplatform.com
  - target:
      kind: ConfigMap
      name: om-access-bridge-config
    patch: |-
      - op: replace
        path: /data/CORS_ALLOWED_ORIGINS
        value: "https://platform.eu-sovereigndataplatform.com"
