apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - minio-cert.yaml          # cert-manager Certificate voor MinIO TLS
  - secretclass-minio-ca.yaml # SecretClass die de CA naar pods levert
  - s3connection-minio.yaml
