"""UWV synthetic data generators.

SYNTHETIC DATA — UWV REFERENCE PLATFORM — NOT FOR REAL USE.
"""

__all__ = [
    "persona",
    "polisadministratie",
    "ww",
    "wia",
    "wajong",
    "zw",
    "crm",
    "fez",
]

SYNTHETIC_HEADER = (
    "# SYNTHETIC DATA — UWV REFERENCE PLATFORM — NOT FOR REAL USE\n"
    "# Generated by data-generation/. Do NOT use for any production purpose.\n"
)
