apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheusrule-uwv.yaml
  - alertmanager-config.yaml
  - pdb-uwv.yaml
  - hpa-trino.yaml
  - opensearch-ilm-job.yaml
  - ingress-prometheus.yaml
