apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheusrule-uwv.yaml
  - alertmanager-config.yaml
  - mailhog.yaml
  - pdb-uwv.yaml
  - hpa-trino.yaml
  - hpa-stateless.yaml
  - opensearch-ilm-job.yaml
  - postgres-backup-cronjob.yaml
  - ingress-prometheus.yaml
  - ingress-grafana.yaml
  - servicemonitor-platform.yaml
  - servicemonitor-openmetadata.yaml
  - vector-log-alerts.yaml
  - podmonitor-vector.yaml
