#!/usr/bin/env python3
"""Render Trino catalog templates op basis van platform-config.yaml.

Source : platform/09-trino/catalogs/*.yaml.tmpl
Output : platform/09-trino/catalogs/rendered/*.yaml + kustomization.yaml

Vervangen placeholders:
  __TABLE_FORMAT__                 -> 'delta' of 'iceberg'
  __TABLE_FORMAT_CONNECTOR_BLOCK__ -> YAML-block voor deltaLake: of iceberg:

Aanroep:
  python3 scripts/render-trino-catalogs.py
  TABLE_FORMAT=iceberg python3 scripts/render-trino-catalogs.py
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import yaml  # PyYAML — vereist (zit in standaard data-engineering-omgeving)

ROOT = Path(__file__).resolve().parents[1]
CFG = ROOT / "platform-config.yaml"
SRC = ROOT / "platform" / "09-trino" / "catalogs"
DST = SRC / "rendered"

CONNECTOR_BLOCK = {
    "delta": (
        "    deltaLake:\n"
        "      metastore:\n"
        "        configMap: uwv-hive\n"
        "      s3:\n"
        "        reference: s3-minio\n"
    ),
    "iceberg": (
        "    iceberg:\n"
        "      metastore:\n"
        "        configMap: uwv-hive\n"
        "      s3:\n"
        "        reference: s3-minio\n"
    ),
}


def resolve_format() -> str:
    fmt = os.environ.get("TABLE_FORMAT")
    if not fmt:
        with CFG.open() as f:
            cfg = yaml.safe_load(f)
        fmt = cfg.get("platform", {}).get("table_format", "delta")
    if fmt not in CONNECTOR_BLOCK:
        sys.exit(f"ERROR: onbekend table_format: {fmt!r} (verwacht 'delta' of 'iceberg')")
    return fmt


def render_one(tmpl: Path, fmt: str) -> Path:
    text = tmpl.read_text()
    text = text.replace("__TABLE_FORMAT_CONNECTOR_BLOCK__", CONNECTOR_BLOCK[fmt].rstrip("\n"))
    text = text.replace("__TABLE_FORMAT__", fmt)
    out = DST / tmpl.with_suffix("").name  # strip .tmpl
    out.write_text(text)
    return out


def write_rendered_kustomization(rendered_files: list[Path]) -> Path:
    """Maak een kustomization.yaml in rendered/ zodat parent kustomize 'em ziet."""
    lines = [
        "# Generated by scripts/render-trino-catalogs.py — niet committen.",
        "apiVersion: kustomize.config.k8s.io/v1beta1",
        "kind: Kustomization",
        "namespace: uwv-platform",
        "resources:",
    ]
    for f in sorted(rendered_files):
        lines.append(f"  - {f.name}")
    out = DST / "kustomization.yaml"
    out.write_text("\n".join(lines) + "\n")
    return out


def main() -> int:
    fmt = resolve_format()
    DST.mkdir(parents=True, exist_ok=True)
    # Schoon rendered-output op voor het regenereren (geen stale files).
    for old in DST.glob("*.yaml"):
        old.unlink()

    templates = sorted(SRC.glob("*.yaml.tmpl"))
    if not templates:
        sys.exit(f"ERROR: geen *.yaml.tmpl gevonden onder {SRC}")

    rendered: list[Path] = []
    for t in templates:
        out = render_one(t, fmt)
        rendered.append(out)
        # Sanity: parse de gerenderde YAML om typo's vroeg te vangen.
        try:
            list(yaml.safe_load_all(out.read_text()))
        except yaml.YAMLError as exc:
            sys.exit(f"ERROR: gerenderde YAML niet parseerbaar: {out}\n{exc}")
        print(f"  rendered  {out.relative_to(ROOT)}  (format={fmt})")

    kfile = write_rendered_kustomization(rendered)
    print(f"  generated {kfile.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
